### PR TITLE
Coder100 dev

### PR DESCRIPTION
**Pull request by cursorweb**
It's about time lol

### CODE REVIEW

**Review by spotandjake — CHANGES_REQUESTED** [review]
This reverts a bunch of changes we have made. i dont see any new additions

**Comment by cursorweb** [comment]
yeah i basically quit
whatever make the branch go stale :((

**Comment by leon332157** [comment]
You need to pull the branch since I updated it.

**Comment by cursorweb** [comment]
oic

anyways i made a new branch

**Pull request closed without merging**
