### PR TITLE
Coder100 features

### PR DESCRIPTION
**Pull request by cursorweb**
These are some features I added.

Here's the synopsis:
- The font should load on all the pages (theme editor, launcher, etc.)
- Formatting should be slightly more standardized towards 4 spaces.
- I highly suggest splitting up the CSS a bit more, there is still way too much js and CSS inside every individual HTML file, particularly the theme editor, making it harder to maintain.

### CODE REVIEW

**Review by CoolCoderSJ — CHANGES_REQUESTED** [review]
you deleted ` src/app/themeHandler/themes.html `, an important part of the app.

**Comment by cursorweb** [comment]
no i didn't what

**Review by CoolCoderSJ — APPROVED** [review]
nvm sorry it said file deleted for me the first time...

**Comment by spotandjake** [comment]
Css, and js in those files are just for now until they are fully finished i have much bigger plans for the editor in the end that will increase usability, and splitting it up makes it a little bit harder to change. as for the picker i plan to slim that down too the big one there is fuse which i dont have time to go and clean up the entire lib atm and having it in a seperate file trips the eslint.

**Review by spotandjake — CHANGES_REQUESTED** [review]
Please update Your npm to version 7 as your package-lock is different. also please use a local font i used helvica and arial as a backup as they look nice and are locally installed meaning a smaller package if people want though we can switch as long as the font is loaded locally.

**Comment by cursorweb** [comment]
hmm
it defaults to a sans-serif font if IBM plex sans is not available

**Comment by spotandjake** [comment]
yah i know can we do two things one include the ibm font and two can we have it be
```
ibm, helvica, ms trebuchia, arial, sans serif    
```
you can add any other in there if you want but that allows us to cover bassically the entire spectrum and only have one font dependency. we dont want to be loading too much from online is all.

**Comment by cursorweb** [comment]
oh ok just a sec

**Comment by cursorweb** [comment]
alright done

**Review by spotandjake — APPROVED** [review]
Should be fine from what i can tell everything is in order.

**Pull request merged**
